[project]
name = "kb-management"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "kb_ingestion",
    "kb_retriever",
    "kb_event_handler"
]

[tool.uv.sources]
kb_ingestion = { workspace = true }
kb_retriever = { workspace = true }
kb_event_handler = { workspace = true }

[tool.setuptools]
packages = []      # root is just a meta project


[tool.uv.workspace]
members = [
    "packages/kb_ingestion",
    "packages/kb_retriever",
    "packages/kb_event_handler",
]
